# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a5b4feee3ad3213d43148c186502e01668ccfa103feb8a522995948af132b889d79a74223f1eca63a6c915565e9c29a10fe41b1607deb9ccda056aa35c12690

test:
  secret_key_base: 5ace8014ab85e6baf1b67d7063342da6f39b0ae8d2e7fac22e7e784f1ea88e5f61307219b8c704f8242012495f482ef0e41daabe5797f383bb632f70576b4db8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
